-- JOIN 과GROUP BY
-- 부서ID , 부서명 테이블과 사원정보 테이블을 JOIN 하여 AVG 구하기
-- PK = DEPT_ID


SELECT E.DEPT_ID
    , D.DEPT_NAME_EN
    , ROUND(AVG(E.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES E
JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY E.DEPT_ID, D.DEPT_NAME_EN
ORDER BY AVG_SAL DESC
